// Ссылка на issue: https://github.com/bpmbpm/rdf-grapher/issues/232

/**
 * SPARQL Queries for Smart Design
 *
 * This module contains all SPARQL queries used in the RDF Grapher application
 * for populating dropdowns and querying RDF data.
 *
 * @file sparql-queries.js
 * @version 8c
 * @date 2026-01-24
 */

/**
 * SPARQL_QUERIES - Коллекция SPARQL запросов для формирования справочников
 * Каждый запрос имеет описание и место использования
 */
const SPARQL_QUERIES = {
    /**
     * Запрос для получения всех индивидов процессов (TypeProcess) в конкретном TriG
     * Используется: Smart Design -> Subject Type = TypeProcess -> Subject dropdown
     * Контекст: VADProcessDia
     */
    PROCESS_INDIVIDUALS_IN_TRIG: (trigUri) => `
        SELECT ?process ?label WHERE {
            GRAPH <${trigUri}> {
                ?process vad:isSubprocessTrig <${trigUri}> .
            }
            GRAPH vad:ptree {
                ?process rdfs:label ?label .
            }
        }
    `,

    /**
     * Запрос для получения всех концептов процессов из ptree
     * Используется: Smart Design -> TriG = ptree -> Subject dropdown
     *               New TriG Modal -> Process Concept dropdown
     * Контекст: ProcessTree (ptree)
     */
    PROCESS_CONCEPTS_IN_PTREE: `
        SELECT ?process ?label WHERE {
            GRAPH vad:ptree {
                ?process rdf:type vad:Process .
                ?process rdfs:label ?label .
            }
        }
    `,

    /**
     * Запрос для получения всех групп исполнителей в конкретном TriG
     * Используется: Smart Design -> Subject Type = ExecutorGroup -> Subject dropdown
     * Контекст: VADProcessDia
     */
    EXECUTOR_GROUPS_IN_TRIG: (trigUri) => `
        SELECT ?group ?label WHERE {
            GRAPH <${trigUri}> {
                ?group rdf:type vad:ExecutorGroup .
                OPTIONAL { ?group rdfs:label ?label }
            }
        }
    `,

    /**
     * Запрос для получения всех исполнителей из rtree
     * Используется: Smart Design -> TriG = rtree -> Subject dropdown
     * Контекст: ExecutorTree (rtree)
     */
    EXECUTORS_IN_RTREE: `
        SELECT ?executor ?label WHERE {
            GRAPH vad:rtree {
                ?executor rdf:type vad:Executor .
                ?executor rdfs:label ?label .
            }
        }
    `,

    /**
     * Запрос для получения предикатов из технологического объекта
     * Используется: Загрузка предикатов из vad-basic-ontology_tech_Appendix.ttl
     * @param {string} techObjectUri - URI технологического объекта (например, vad:IndividProcessPredicate)
     */
    PREDICATES_FROM_TECH_OBJECT: (techObjectUri) => `
        SELECT ?predicate WHERE {
            <${techObjectUri}> vad:includePredicate ?predicate .
        }
    `,

    /**
     * Запрос для получения автоматически генерируемых предикатов
     * Используется: Определение disabled опций в Predicate dropdown
     * @param {string} techObjectUri - URI технологического объекта
     */
    AUTO_GENERATED_PREDICATES: (techObjectUri) => `
        SELECT ?predicate WHERE {
            <${techObjectUri}> vad:autoGeneratedPredicate ?predicate .
        }
    `,

    /**
     * Запрос для получения концептов процессов без TriG схемы
     * Используется: New TriG Modal - показывает процессы, которые ещё не имеют схемы
     */
    PROCESS_CONCEPTS_WITHOUT_TRIG: `
        SELECT ?process ?label WHERE {
            GRAPH vad:ptree {
                ?process rdf:type vad:Process .
                ?process rdfs:label ?label .
                FILTER NOT EXISTS { ?process vad:hasTrig ?trig }
            }
        }
    `
};
